// Comprehensive Thesaurus for Academic & General Writing
// Organized by word category for efficient lookup

const thesaurus: Record<string, string[]> = {
  // Common verbs
  'say': ['state', 'express', 'mention', 'declare', 'announce', 'assert', 'claim', 'propose', 'suggest', 'indicate'],
  'said': ['stated', 'expressed', 'mentioned', 'declared', 'announced', 'asserted', 'claimed', 'proposed', 'suggested', 'indicated'],
  'think': ['believe', 'consider', 'suppose', 'assume', 'presume', 'conceive', 'deem', 'regard', 'reckon', 'maintain'],
  'thought': ['believed', 'considered', 'supposed', 'assumed', 'presumed', 'conceived', 'deemed', 'regarded', 'reckoned', 'maintained'],
  'get': ['obtain', 'acquire', 'receive', 'secure', 'gain', 'procure', 'attain', 'retrieve', 'fetch', 'collect'],
  'got': ['obtained', 'acquired', 'received', 'secured', 'gained', 'procured', 'attained', 'retrieved', 'fetched', 'collected'],
  'make': ['create', 'produce', 'construct', 'fabricate', 'manufacture', 'build', 'generate', 'form', 'establish', 'develop'],
  'made': ['created', 'produced', 'constructed', 'fabricated', 'manufactured', 'built', 'generated', 'formed', 'established', 'developed'],
  'go': ['proceed', 'advance', 'move', 'travel', 'progress', 'venture', 'depart', 'journey', 'traverse', 'shift'],
  'went': ['proceeded', 'advanced', 'moved', 'traveled', 'progressed', 'ventured', 'departed', 'journeyed', 'traversed', 'shifted'],
  'see': ['observe', 'perceive', 'notice', 'witness', 'discern', 'behold', 'view', 'sight', 'recognize', 'detect'],
  'saw': ['observed', 'perceived', 'noticed', 'witnessed', 'discerned', 'beheld', 'viewed', 'sighted', 'recognized', 'detected'],
  'know': ['understand', 'comprehend', 'recognize', 'acknowledge', 'apprehend', 'perceive', 'grasp', 'realize', 'discern', 'fathom'],
  'knew': ['understood', 'comprehended', 'recognized', 'acknowledged', 'apprehended', 'perceived', 'grasped', 'realized', 'discerned', 'fathomed'],
  'want': ['desire', 'wish', 'need', 'require', 'crave', 'seek', 'long', 'yearn', 'covet', 'prefer'],
  'wanted': ['desired', 'wished', 'needed', 'required', 'craved', 'sought', 'longed', 'yearned', 'coveted', 'preferred'],
  'use': ['employ', 'utilize', 'apply', 'exploit', 'exercise', 'operate', 'deploy', 'implement', 'wield', 'harness'],
  'used': ['employed', 'utilized', 'applied', 'exploited', 'exercised', 'operated', 'deployed', 'implemented', 'wielded', 'harnessed'],
  'try': ['attempt', 'endeavor', 'strive', 'seek', 'essay', 'undertake', 'venture', 'test', 'experiment', 'assay'],
  'tried': ['attempted', 'endeavored', 'strived', 'sought', 'essayed', 'undertook', 'ventured', 'tested', 'experimented', 'assayed'],
  'show': ['display', 'reveal', 'demonstrate', 'exhibit', 'illustrate', 'present', 'expose', 'manifest', 'depict', 'portray'],
  'showed': ['displayed', 'revealed', 'demonstrated', 'exhibited', 'illustrated', 'presented', 'exposed', 'manifested', 'depicted', 'portrayed'],
  'find': ['discover', 'locate', 'uncover', 'detect', 'identify', 'ascertain', 'retrieve', 'encounter', 'stumble', 'expose'],
  'give': ['provide', 'supply', 'grant', 'offer', 'donate', 'bestow', 'impart', 'present', 'deliver', 'furnish'],
  'gave': ['provided', 'supplied', 'granted', 'offered', 'donated', 'bestowed', 'imparted', 'presented', 'delivered', 'furnished'],
  'tell': ['inform', 'notify', 'advise', 'report', 'communicate', 'disclose', 'relate', 'recount', 'articulate', 'convey'],
  'told': ['informed', 'notified', 'advised', 'reported', 'communicated', 'disclosed', 'related', 'recounted', 'articulated', 'conveyed'],
  'become': ['transform', 'evolve', 'develop', 'grow', 'turn', 'convert', 'shift', 'transition', 'metamorphose', 'mature'],
  'became': ['transformed', 'evolved', 'developed', 'grew', 'turned', 'converted', 'shifted', 'transitioned', 'metamorphosed', 'matured'],
  'work': ['labor', 'toil', 'operate', 'function', 'perform', 'engage', 'serve', 'execute', 'proceed', 'succeed'],
  'worked': ['labored', 'toiled', 'operated', 'functioned', 'performed', 'engaged', 'served', 'executed', 'proceeded', 'succeeded'],
  'call': ['name', 'designate', 'label', 'term', 'style', 'dub', 'summon', 'contact', 'appeal', 'invoke'],
  'called': ['named', 'designated', 'labeled', 'termed', 'styled', 'dubbed', 'summoned', 'contacted', 'appealed', 'invoked'],
  'ask': ['inquire', 'question', 'interrogate', 'query', 'pose', 'solicit', 'request', 'appeal', 'demand', 'petition'],
  'asked': ['inquired', 'questioned', 'interrogated', 'queried', 'posed', 'solicited', 'requested', 'appealed', 'demanded', 'petitioned'],
  'help': ['assist', 'aid', 'support', 'facilitate', 'contribute', 'benefit', 'serve', 'succor', 'relieve', 'promote'],
  'helped': ['assisted', 'aided', 'supported', 'facilitated', 'contributed', 'benefited', 'served', 'succored', 'relieved', 'promoted'],
  'talk': ['converse', 'communicate', 'dialogue', 'discuss', 'chat', 'discourse', 'speak', 'interact', 'confer', 'consult'],
  'talked': ['conversed', 'communicated', 'dialogued', 'discussed', 'chatted', 'discoursed', 'spoke', 'interacted', 'conferred', 'consulted'],
  'turn': ['rotate', 'spin', 'revolve', 'pivot', 'shift', 'convert', 'transform', 'direct', 'orient', 'maneuver'],
  'turned': ['rotated', 'spun', 'revolved', 'pivoted', 'shifted', 'converted', 'transformed', 'directed', 'oriented', 'maneuvered'],
  'start': ['begin', 'commence', 'initiate', 'launch', 'embark', 'trigger', 'open', 'establish', 'introduce', 'undertake'],
  'started': ['began', 'commenced', 'initiated', 'launched', 'embarked', 'triggered', 'opened', 'established', 'introduced', 'undertook'],
  'keep': ['retain', 'maintain', 'preserve', 'sustain', 'uphold', 'persist', 'continue', 'harbor', 'store', 'hold'],
  'kept': ['retained', 'maintained', 'preserved', 'sustained', 'upheld', 'persisted', 'continued', 'harbored', 'stored', 'held'],
  'follow': ['pursue', 'track', 'trail', 'chase', 'adhere', 'observe', 'comply', 'emulate', 'succeed', 'ensue'],
  'followed': ['pursued', 'tracked', 'trailed', 'chased', 'adhered', 'observed', 'complied', 'emulated', 'succeeded', 'ensued'],
  'allow': ['permit', 'enable', 'authorize', 'consent', 'grant', 'tolerate', 'afford', 'sanction', 'empower', 'facilitate'],
  'allowed': ['permitted', 'enabled', 'authorized', 'consented', 'granted', 'tolerated', 'afforded', 'sanctioned', 'empowered', 'facilitated'],
  'add': ['append', 'attach', 'annex', 'incorporate', 'adjoin', 'combine', 'sum', 'increase', 'supplement', 'augment'],
  'added': ['appended', 'attached', 'annexed', 'incorporated', 'adjoined', 'combined', 'summed', 'increased', 'supplemented', 'augmented'],
  'spend': ['expend', 'consume', 'invest', 'disburse', 'allocate', 'squander', 'waste', 'exhaust', 'deplete', 'employ'],
  'spent': ['expended', 'consumed', 'invested', 'disbursed', 'allocated', 'squandered', 'wasted', 'exhausted', 'depleted', 'employed'],
  'write': ['compose', 'author', 'draft', 'inscribe', 'scribe', 'pen', 'record', 'document', 'articulate', 'express'],
  'wrote': ['composed', 'authored', 'drafted', 'inscribed', 'scribed', 'penned', 'recorded', 'documented', 'articulated', 'expressed'],
  'read': ['peruse', 'scan', 'skim', 'study', 'review', 'examine', 'interpret', 'decipher', 'absorb', 'understand'],
  'develop': ['expand', 'evolve', 'advance', 'progress', 'mature', 'cultivate', 'construct', 'elaborate', 'unfold', 'refine'],
  'provide': ['supply', 'furnish', 'offer', 'afford', 'grant', 'yield', 'contribute', 'deliver', 'render', 'present'],
  'increase': ['augment', 'expand', 'enhance', 'amplify', 'enlarge', 'escalate', 'boost', 'elevate', 'heighten', 'intensify'],
  'improve': ['enhance', 'ameliorate', 'refine', 'upgrade', 'strengthen', 'perfect', 'optimize', 'better', 'advance', 'elevate'],
  'continue': ['persist', 'proceed', 'maintain', 'sustain', 'prolong', 'extend', 'resume', 'persevere', 'perpetuate', 'endure'],
  'change': ['alter', 'modify', 'transform', 'convert', 'adjust', 'revise', 'vary', 'shift', 'amend', 'adapt'],
  'explain': ['clarify', 'elucidate', 'expound', 'interpret', 'illuminate', 'detail', 'articulate', 'describe', 'account', 'justify'],
  'analyze': ['examine', 'investigate', 'scrutinize', 'study', 'dissect', 'evaluate', 'assess', 'appraise', 'critique', 'parse'],
  'conclude': ['finish', 'end', 'complete', 'terminate', 'close', 'determine', 'infer', 'deduce', 'resolve', 'finalize'],
  'suggest': ['propose', 'recommend', 'indicate', 'imply', 'intimate', 'insinuate', 'hint', 'advise', 'counsel', 'urge'],
  'examine': ['inspect', 'scrutinize', 'investigate', 'study', 'survey', 'check', 'explore', 'analyze', 'assess', 'review'],
  'support': ['uphold', 'sustain', 'buttress', 'corroborate', 'validate', 'endorse', 'back', 'champion', 'defend', 'strengthen'],
  'argue': ['contend', 'assert', 'maintain', 'debate', 'dispute', 'reason', 'plead', 'advocate', 'present', 'submit'],
  'prove': ['demonstrate', 'establish', 'verify', 'validate', 'confirm', 'substantiate', 'authenticate', 'document', 'justify', 'show'],

  // Common adjectives
  'good': ['excellent', 'fine', 'superior', 'quality', 'positive', 'beneficial', 'favorable', 'admirable', 'commendable', 'outstanding'],
  'bad': ['poor', 'inferior', 'unfavorable', 'negative', 'detrimental', 'undesirable', 'adverse', 'harmful', 'inadequate', 'deficient'],
  'big': ['large', 'vast', 'extensive', 'enormous', 'immense', 'substantial', 'considerable', 'significant', 'monumental', 'tremendous'],
  'small': ['tiny', 'petite', 'diminutive', 'miniature', 'insignificant', 'negligible', 'minimal', 'meager', 'scanty', 'modest'],
  'important': ['significant', 'crucial', 'essential', 'vital', 'critical', 'fundamental', 'paramount', 'central', 'principal', 'chief'],
  'interesting': ['engaging', 'compelling', 'fascinating', 'captivating', 'intriguing', 'absorbing', 'engrossing', 'enthralling', 'gripping', 'riveting'],
  'different': ['distinct', 'various', 'diverse', 'dissimilar', 'divergent', 'disparate', 'heterogeneous', 'unlike', 'differential', 'variant'],
  'strong': ['robust', 'powerful', 'vigorous', 'sturdy', 'formidable', 'potent', 'forceful', 'resilient', 'muscular', 'mighty'],
  'weak': ['frail', 'feeble', 'fragile', 'delicate', 'infirm', 'powerless', 'impotent', 'vulnerable', 'insubstantial', 'tenuous'],
  'clear': ['distinct', 'lucid', 'transparent', 'unambiguous', 'evident', 'obvious', 'apparent', 'plain', 'manifest', 'perspicuous'],
  'difficult': ['challenging', 'arduous', 'tough', 'complex', 'complicated', 'intricate', 'demanding', 'formidable', 'laborious', 'onerous'],
  'easy': ['simple', 'effortless', 'straightforward', 'facile', 'uncomplicated', 'elementary', 'basic', 'undemanding', 'painless', 'convenient'],
  'fast': ['swift', 'rapid', 'quick', 'speedy', 'hasty', 'expeditious', 'brisk', 'prompt', 'fleet', 'accelerated'],
  'slow': ['sluggish', 'gradual', 'leisurely', 'dilatory', 'tardy', 'dawdling', 'unhurried', 'deliberate', 'pokey', 'lagging'],
  'happy': ['joyful', 'cheerful', 'content', 'delighted', 'pleased', 'elated', 'jubilant', 'blissful', 'ecstatic', 'satisfied'],
  'sad': ['sorrowful', 'melancholic', 'dejected', 'despondent', 'forlorn', 'mournful', 'disconsolate', 'gloomy', 'downcast', 'crestfallen'],
  'new': ['novel', 'recent', 'fresh', 'modern', 'contemporary', 'original', 'unprecedented', 'latest', 'up-to-date', 'innovative'],
  'old': ['ancient', 'archaic', 'obsolete', 'dated', 'outmoded', 'venerable', 'aged', 'antique', 'timeworn', 'antiquated'],
  'beautiful': ['lovely', 'gorgeous', 'stunning', 'handsome', 'attractive', 'exquisite', 'elegant', 'picturesque', 'radiant', 'sublime'],
  'ugly': ['hideous', 'unsightly', 'grotesque', 'repugnant', 'dreadful', 'abominable', 'repulsive', 'ghastly', 'unattractive', 'homely'],
  'common': ['frequent', 'typical', 'ordinary', 'usual', 'standard', 'conventional', 'prevalent', 'widespread', 'routine', 'mundane'],
  'rare': ['uncommon', 'infrequent', 'scarce', 'exceptional', 'unique', 'singular', 'unusual', 'remarkable', 'sporadic', 'seldom'],
  'true': ['accurate', 'correct', 'factual', 'genuine', 'authentic', 'veracious', 'valid', 'legitimate', 'sincere', 'honest'],
  'false': ['incorrect', 'inaccurate', 'untrue', 'erroneous', 'fraudulent', 'fabricated', 'spurious', 'counterfeit', 'deceptive', 'misleading'],
  'possible': ['feasible', 'viable', 'probable', 'conceivable', 'plausible', 'achievable', 'attainable', 'potential', 'imaginable', 'realistic'],
  'impossible': ['infeasible', 'implausible', 'unattainable', 'improbable', 'inconceivable', 'unrealistic', 'unthinkable', 'unworkable', 'unachievable', 'hopeless'],
  'certain': ['sure', 'definite', 'absolute', 'positive', 'convinced', 'confident', 'undoubted', 'inevitable', 'assured', 'indisputable'],
  'uncertain': ['unsure', 'doubtful', 'indefinite', 'questionable', 'ambiguous', 'unclear', 'hesitant', 'tentative', 'inconclusive', 'vague'],
  'serious': ['grave', 'solemn', 'earnest', 'somber', 'weighty', 'significant', 'critical', 'severe', 'consequential', 'momentous'],
  'funny': ['humorous', 'amusing', 'witty', 'comic', 'hilarious', 'entertaining', 'droll', 'laughable', 'whimsical', 'facetious'],
  'busy': ['occupied', 'engaged', 'preoccupied', 'absorbed', 'involved', 'hard-working', 'industrious', 'active', 'hectic', 'rushed'],
  'idle': ['inactive', 'unemployed', 'unoccupied', 'lazy', 'indolent', 'slothful', 'dormant', 'unused', 'vacant', 'stagnant'],

  // Common nouns
  'thing': ['object', 'item', 'entity', 'matter', 'affair', 'concern', 'issue', 'element', 'component', 'aspect'],
  'person': ['individual', 'human', 'being', 'character', 'subject', 'figure', 'specimen', 'agent', 'entity', 'soul'],
  'people': ['individuals', 'humans', 'beings', 'persons', 'folks', 'populace', 'citizenry', 'society', 'community', 'collective'],
  'time': ['period', 'era', 'epoch', 'age', 'season', 'moment', 'instant', 'duration', 'interval', 'span'],
  'way': ['method', 'manner', 'approach', 'technique', 'mode', 'means', 'procedure', 'pathway', 'direction', 'fashion'],
  'idea': ['concept', 'notion', 'thought', 'conception', 'premise', 'theory', 'hypothesis', 'perception', 'viewpoint', 'principle'],
  'problem': ['issue', 'difficulty', 'challenge', 'obstacle', 'complication', 'dilemma', 'predicament', 'situation', 'concern', 'matter'],
  'reason': ['cause', 'motive', 'rationale', 'basis', 'ground', 'factor', 'explanation', 'justification', 'purpose', 'incentive'],
  'question': ['inquiry', 'query', 'interrogation', 'issue', 'doubt', 'concern', 'uncertainty', 'puzzle', 'riddle', 'problem'],
  'answer': ['response', 'reply', 'solution', 'resolution', 'explanation', 'result', 'outcome', 'conclusion', 'decision', 'remedy'],
  'result': ['consequence', 'outcome', 'effect', 'conclusion', 'product', 'finding', 'discovery', 'output', 'upshot', 'sequel'],
  'system': ['structure', 'organization', 'framework', 'scheme', 'setup', 'mechanism', 'network', 'apparatus', 'arrangement', 'complex'],
  'research': ['investigation', 'study', 'inquiry', 'examination', 'exploration', 'analysis', 'experimentation', 'survey', 'scholarship', 'scrutiny'],
  'evidence': ['proof', 'data', 'testimony', 'documentation', 'indication', 'support', 'basis', 'corroboration', 'grounds', 'substantiation'],
  'knowledge': ['understanding', 'awareness', 'information', 'learning', 'wisdom', 'expertise', 'familiarity', 'comprehension', 'erudition', 'scholarship'],
  'experience': ['encounter', 'exposure', 'involvement', 'practice', 'background', 'ordeal', 'event', 'occurrence', 'incident', 'journey'],
  'opinion': ['view', 'perspective', 'stance', 'belief', 'judgment', 'assessment', 'conviction', 'standpoint', 'sentiment', 'impression'],
  'discussion': ['debate', 'dialogue', 'conversation', 'talk', 'discourse', 'exchange', 'consultation', 'conference', 'colloquy', 'parley'],
  'example': ['instance', 'illustration', 'specimen', 'sample', 'case', 'precedent', 'exemplar', 'model', 'paradigm', 'demonstration'],
  'effect': ['consequence', 'result', 'outcome', 'impact', 'influence', 'reaction', 'repercussion', 'ramification', 'aftermath', 'sequela'],
  'cause': ['reason', 'source', 'origin', 'root', 'basis', 'factor', 'stimulus', 'antecedent', 'agent', 'determinant'],
  'benefit': ['advantage', 'gain', 'profit', 'asset', 'plus', 'merit', 'value', 'blessing', 'boon', 'perk'],
  'cost': ['expense', 'price', 'charge', 'expenditure', 'fee', 'payment', 'outlay', 'toll', 'rate', 'tariff'],
  'level': ['degree', 'extent', 'stage', 'grade', 'rank', 'tier', 'plane', 'standard', 'height', 'magnitude'],
  'issue': ['matter', 'question', 'topic', 'subject', 'concern', 'point', 'problem', 'debate', 'publication', 'edition'],
  'point': ['spot', 'location', 'position', 'place', 'dot', 'mark', 'tip', 'detail', 'argument', 'assertion'],
  'role': ['function', 'part', 'position', 'job', 'duty', 'task', 'capacity', 'purpose', 'responsibility', 'character'],
  'rule': ['regulation', 'law', 'principle', 'norm', 'standard', 'guideline', 'decree', 'statute', 'ordinance', 'policy'],
  'value': ['worth', 'importance', 'merit', 'quality', 'principle', 'standard', 'cost', 'price', 'amount', 'significance'],
  'type': ['kind', 'category', 'class', 'variety', 'form', 'sort', 'genre', 'style', 'character', 'species'],
  'basis': ['foundation', 'ground', 'reason', 'premise', 'principle', 'root', 'core', 'essence', 'background', 'source'],
  'state': ['condition', 'situation', 'status', 'position', 'phase', 'stage', 'state of being', 'circumstances', 'estate', 'realm'],

  // Academic/Research terms
  // Academic/Research terms
  'significant': ['substantial', 'meaningful', 'considerable', 'noteworthy', 'material', 'relevant', 'impactful', 'pivotal', 'critical', 'consequential'],
  'data': ['information', 'facts', 'figures', 'statistics', 'evidence', 'findings', 'results', 'observations', 'measurements', 'records'],
  'hypothesis': ['theory', 'supposition', 'assumption', 'proposition', 'conjecture', 'premise', 'postulate', 'guess', 'educated guess', 'tentative explanation'],
  'theory': ['hypothesis', 'explanation', 'framework', 'model', 'concept', 'doctrine', 'school of thought', 'system of ideas', 'philosophy', 'principle'],
  'method': ['approach', 'technique', 'procedure', 'methodology', 'process', 'system', 'strategy', 'way', 'means', 'mode'],
  'process': ['procedure', 'method', 'system', 'operation', 'course', 'technique', 'routine', 'approach', 'mechanism', 'protocol'],
  'analysis': ['examination', 'investigation', 'study', 'breakdown', 'assessment', 'evaluation', 'scrutiny', 'inspection', 'appraisal', 'dissection'],
  'conclusion': ['finding', 'determination', 'judgment', 'verdict', 'decision', 'outcome', 'result', 'inference', 'deduction', 'resolution'],
  'observation': ['remark', 'comment', 'note', 'notation', 'finding', 'discovery', 'sighting', 'perception', 'insight', 'indication'],
  'demonstrate': ['show', 'prove', 'exhibit', 'illustrate', 'display', 'reveal', 'manifest', 'establish', 'substantiate', 'validate'],
  'illustrate': ['exemplify', 'demonstrate', 'show', 'depict', 'represent', 'explain', 'clarify', 'elucidate', 'illuminate', 'visualize'],
  'summarize': ['recapitulate', 'outline', 'encapsulate', 'synopsize', 'abstract', 'condense', 'abbreviate', 'overview', 'epitomize', 'conclude'],
  'compare': ['contrast', 'juxtapose', 'differentiate', 'examine', 'parallel', 'match', 'relate', 'associate', 'equate', 'measure'],
  'evaluate': ['assess', 'appraise', 'judge', 'critique', 'rate', 'estimate', 'measure', 'examine', 'consider', 'analyze'],
  'indicate': ['suggest', 'imply', 'show', 'demonstrate', 'reveal', 'signal', 'display', 'mark', 'manifest', 'denote'],
  'relevant': ['applicable', 'pertinent', 'apposite', 'germane', 'material', 'significant', 'apropos', 'connected', 'related', 'appropriate'],
  'comprehensive': ['complete', 'thorough', 'exhaustive', 'all-inclusive', 'extensive', 'broad', 'detailed', 'full-scale', 'encyclopedic', 'systematic'],
  'precise': ['exact', 'accurate', 'meticulous', 'careful', 'punctilious', 'specific', 'definite', 'particular', 'explicit', 'strict'],
  'elaborate': ['detailed', 'complex', 'intricate', 'complicated', 'ornate', 'extensive', 'thorough', 'involved', 'sophisticated', 'refined'],
  'framework': ['structure', 'system', 'skeleton', 'scaffold', 'model', 'outline', 'basis', 'foundation', 'scheme', 'apparatus'],

  // Transition words
  'however': ['nevertheless', 'nonetheless', 'still', 'yet', 'but', 'though', 'even so', 'all the same', 'on the other hand', 'in contrast'],
  'therefore': ['thus', 'accordingly', 'consequently', 'hence', 'as a result', 'for this reason', 'so', 'thereby', 'subsequently', 'ergo'],
  'because': ['since', 'as', 'due to', 'caused by', 'on account of', 'owing to', 'inasmuch as', 'given that', 'in view of', 'by reason of'],
  'moreover': ['furthermore', 'additionally', 'besides', 'also', 'in addition', 'what is more', 'further', 'on top of that', 'over and above', 'plus'],
  'also': ['as well', 'too', 'besides', 'additionally', 'furthermore', 'moreover', 'in addition', 'likewise', 'equally', 'further'],
  'although': ['though', 'even though', 'while', 'whereas', 'despite', 'in spite of', 'notwithstanding', 'yet', 'but', 'however'],
  'through': ['via', 'by means of', 'by way of', 'using', 'with', 'employing', 'utilizing', 'by', 'throughout', 'across'],
  'according': ['based on', 'as stated by', 'per', 'by', 'pursuant to', 'in accordance with', 'consistent with', 'in line with', 'aligned with', 'as reported by'],
  
  // Expanded Academic & Common Words (300+ additions)
  'affect': ['influence', 'impact', 'shape', 'modify', 'alter', 'sway', 'transform', 'touch', 'change', 'determine'],
  'approach': ['method', 'technique', 'strategy', 'way', 'means', 'procedure', 'tactic', 'manner', 'path', 'course'],
  'area': ['field', 'domain', 'sphere', 'region', 'zone', 'sector', 'territory', 'realm', 'scope', 'discipline'],
  'assess': ['evaluate', 'judge', 'appraise', 'measure', 'determine', 'estimate', 'gauge', 'rate', 'review', 'weigh'],
  'assume': ['suppose', 'presume', 'believe', 'expect', 'think', 'take for granted', 'postulate', 'hypothesize', 'conjecture', 'infer'],
  'authority': ['power', 'control', 'command', 'jurisdiction', 'influence', 'dominion', 'expert', 'specialist', 'professional', 'source'],
  'available': ['accessible', 'obtainable', 'ready', 'at hand', 'usable', 'present', 'free', 'on hand', 'handy', 'convenient'],
  'concept': ['idea', 'notion', 'theory', 'thought', 'principle', 'conception', 'construct', 'hypothesis', 'abstraction', 'belief'],
  'consist': ['comprise', 'contain', 'include', 'incorporate', 'be made up of', 'be composed of', 'encompass', 'constitute', 'embody', 'involve'],
  'constitute': ['form', 'make up', 'compose', 'comprise', 'establish', 'create', 'amount to', 'represent', 'embody', 'equal'],
  'context': ['setting', 'environment', 'background', 'framework', 'circumstances', 'situation', 'conditions', 'milieu', 'scene', 'backdrop'],
  'contract': ['agreement', 'deal', 'pact', 'treaty', 'arrangement', 'compact', 'covenant', 'accord', 'settlement', 'understanding'],
  'create': ['make', 'produce', 'generate', 'form', 'establish', 'construct', 'build', 'develop', 'originate', 'design'],
  'define': ['explain', 'describe', 'clarify', 'specify', 'characterize', 'determine', 'delimit', 'outline', 'identify', 'interpret'],
  'derive': ['obtain', 'extract', 'draw', 'deduce', 'infer', 'originate', 'stem', 'come from', 'get', 'trace'],
  'design': ['plan', 'create', 'develop', 'devise', 'conceive', 'formulate', 'draft', 'blueprint', 'scheme', 'arrange'],
  'distribute': ['allocate', 'dispense', 'spread', 'deliver', 'supply', 'hand out', 'disseminate', 'circulate', 'divide', 'share'],
  'economy': ['financial system', 'market', 'commerce', 'trade', 'business', 'thrift', 'efficiency', 'saving', 'frugality', 'prudence'],
  'environment': ['surroundings', 'setting', 'context', 'habitat', 'milieu', 'conditions', 'atmosphere', 'situation', 'background', 'locale'],
  'establish': ['create', 'found', 'set up', 'institute', 'form', 'build', 'prove', 'demonstrate', 'confirm', 'validate'],
  'estimate': ['calculate', 'approximate', 'assess', 'gauge', 'reckon', 'evaluate', 'judge', 'determine', 'compute', 'guess'],
  'evident': ['clear', 'obvious', 'apparent', 'plain', 'visible', 'manifest', 'noticeable', 'distinct', 'patent', 'unmistakable'],
  'export': ['send abroad', 'ship out', 'trade', 'sell overseas', 'dispatch', 'transmit', 'transport', 'market abroad', 'convey', 'forward'],
  'factor': ['element', 'component', 'aspect', 'feature', 'consideration', 'circumstance', 'detail', 'part', 'variable', 'influence'],
  'feature': ['characteristic', 'trait', 'quality', 'attribute', 'aspect', 'element', 'facet', 'property', 'mark', 'component'],
  'final': ['last', 'ultimate', 'concluding', 'terminal', 'ending', 'closing', 'eventual', 'definitive', 'conclusive', 'decisive'],
  'focus': ['concentrate', 'center', 'emphasize', 'spotlight', 'highlight', 'direct', 'target', 'home in on', 'zero in on', 'fixate'],
  'formula': ['equation', 'expression', 'rule', 'method', 'recipe', 'prescription', 'procedure', 'protocol', 'blueprint', 'model'],
  'function': ['purpose', 'role', 'use', 'task', 'job', 'duty', 'operate', 'work', 'serve', 'act'],
  'identify': ['recognize', 'determine', 'discover', 'find', 'pinpoint', 'detect', 'establish', 'locate', 'distinguish', 'name'],
  'income': ['earnings', 'revenue', 'wages', 'salary', 'pay', 'profits', 'proceeds', 'gain', 'receipts', 'compensation'],
  'individual': ['person', 'single', 'particular', 'separate', 'distinct', 'unique', 'specific', 'discrete', 'lone', 'sole'],
  'interpret': ['explain', 'understand', 'decode', 'translate', 'clarify', 'elucidate', 'construe', 'read', 'analyze', 'define'],
  'involve': ['include', 'contain', 'encompass', 'comprise', 'entail', 'require', 'necessitate', 'incorporate', 'engage', 'concern'],
  'labor': ['work', 'toil', 'effort', 'workforce', 'workers', 'employees', 'exertion', 'industry', 'employment', 'task'],
  'legal': ['lawful', 'legitimate', 'valid', 'authorized', 'permitted', 'licit', 'constitutional', 'juridical', 'statutory', 'allowed'],
  'legislate': ['enact', 'pass laws', 'make laws', 'establish', 'decree', 'ordain', 'regulate', 'codify', 'formalize', 'authorize'],
  'major': ['main', 'principal', 'primary', 'chief', 'key', 'leading', 'significant', 'important', 'central', 'crucial'],
  'maintain': ['preserve', 'keep', 'sustain', 'uphold', 'continue', 'retain', 'support', 'assert', 'claim', 'declare'],
  'normal': ['usual', 'typical', 'standard', 'regular', 'ordinary', 'common', 'conventional', 'average', 'customary', 'routine'],
  'obtain': ['get', 'acquire', 'gain', 'secure', 'procure', 'attain', 'receive', 'achieve', 'earn', 'win'],
  'occur': ['happen', 'take place', 'arise', 'transpire', 'come about', 'emerge', 'appear', 'materialize', 'develop', 'result'],
  'percent': ['percentage', 'proportion', 'ratio', 'fraction', 'share', 'portion', 'part', 'rate', 'quota', 'measure'],
  'period': ['time', 'span', 'duration', 'interval', 'phase', 'stage', 'era', 'epoch', 'term', 'cycle'],
  'policy': ['plan', 'strategy', 'approach', 'guideline', 'procedure', 'protocol', 'rule', 'regulation', 'course', 'position'],
  'principle': ['rule', 'law', 'doctrine', 'tenet', 'belief', 'concept', 'standard', 'axiom', 'foundation', 'truth'],
  'proceed': ['continue', 'advance', 'progress', 'go ahead', 'move forward', 'carry on', 'go on', 'pursue', 'persevere', 'press on'],
  'purchase': ['buy', 'acquire', 'obtain', 'procure', 'secure', 'get', 'invest in', 'pay for', 'shop for', 'pick up'],
  'range': ['variety', 'spectrum', 'span', 'scope', 'extent', 'reach', 'spread', 'array', 'gamut', 'selection'],
  'regulate': ['control', 'govern', 'manage', 'direct', 'supervise', 'oversee', 'administer', 'monitor', 'standardize', 'adjust'],
  'reside': ['live', 'dwell', 'inhabit', 'stay', 'lodge', 'occupy', 'settle', 'abide', 'remain', 'domicile'],
  'resource': ['asset', 'means', 'supply', 'reserve', 'source', 'facility', 'material', 'capital', 'wealth', 'stock'],
  'respond': ['reply', 'answer', 'react', 'acknowledge', 'counter', 'retort', 'return', 'reciprocate', 'feedback', 'correspond'],
  'restrict': ['limit', 'constrain', 'confine', 'restrain', 'curtail', 'control', 'regulate', 'bound', 'circumscribe', 'inhibit'],
  'section': ['part', 'segment', 'portion', 'division', 'component', 'piece', 'unit', 'chapter', 'passage', 'fragment'],
  'sector': ['area', 'field', 'division', 'segment', 'zone', 'region', 'department', 'branch', 'sphere', 'industry'],
  'secure': ['safe', 'protected', 'defended', 'obtain', 'acquire', 'get', 'ensure', 'guarantee', 'lock', 'fasten'],
  'seek': ['search', 'look for', 'pursue', 'hunt', 'quest', 'try', 'attempt', 'strive', 'aim', 'endeavor'],
  'select': ['choose', 'pick', 'elect', 'opt for', 'decide on', 'single out', 'prefer', 'designate', 'determine', 'nominate'],
  'shift': ['change', 'move', 'transfer', 'switch', 'alter', 'transition', 'convert', 'transform', 'relocate', 'displace'],
  'site': ['location', 'place', 'position', 'spot', 'venue', 'area', 'locality', 'setting', 'scene', 'point'],
  'source': ['origin', 'root', 'cause', 'basis', 'foundation', 'reference', 'authority', 'wellspring', 'derivation', 'provenance'],
  'specific': ['particular', 'precise', 'exact', 'definite', 'explicit', 'clear', 'distinct', 'special', 'unique', 'detailed'],
  'structure': ['framework', 'organization', 'system', 'arrangement', 'construction', 'form', 'design', 'configuration', 'format', 'composition'],
  'sufficient': ['enough', 'adequate', 'ample', 'satisfactory', 'acceptable', 'suitable', 'plentiful', 'decent', 'competent', 'tolerable'],
  'technology': ['tech', 'innovation', 'advancement', 'machinery', 'equipment', 'tools', 'systems', 'apparatus', 'devices', 'mechanisms'],
  'text': ['writing', 'document', 'passage', 'content', 'words', 'script', 'manuscript', 'material', 'literature', 'body'],
  'transfer': ['move', 'shift', 'relocate', 'transport', 'convey', 'transmit', 'send', 'pass', 'hand over', 'assign'],
  'vary': ['differ', 'change', 'fluctuate', 'diverge', 'deviate', 'alter', 'modify', 'shift', 'range', 'diversify'],
  'achieve': ['accomplish', 'attain', 'reach', 'realize', 'obtain', 'gain', 'succeed', 'complete', 'fulfill', 'secure'],
  'acquire': ['obtain', 'get', 'gain', 'procure', 'secure', 'attain', 'receive', 'earn', 'collect', 'gather'],
  'administer': ['manage', 'run', 'direct', 'supervise', 'control', 'govern', 'oversee', 'conduct', 'operate', 'execute'],
  'adult': ['grown-up', 'mature', 'grownup', 'full-grown', 'of age', 'developed', 'responsible', 'independent', 'elder', 'senior'],
  'advocate': ['support', 'champion', 'promote', 'back', 'endorse', 'recommend', 'defend', 'uphold', 'argue for', 'sponsor'],
  'aid': ['help', 'assist', 'support', 'facilitate', 'contribute', 'succor', 'relief', 'benefit', 'serve', 'advance'],
  'albeit': ['although', 'though', 'even though', 'while', 'notwithstanding', 'despite', 'in spite of', 'granted', 'admittedly', 'still'],
  'allocate': ['assign', 'distribute', 'designate', 'allot', 'apportion', 'dispense', 'divide', 'share', 'earmark', 'grant'],
  'alter': ['change', 'modify', 'adjust', 'vary', 'transform', 'revise', 'adapt', 'convert', 'amend', 'shift'],
  'alternative': ['option', 'choice', 'substitute', 'replacement', 'backup', 'different', 'other', 'secondary', 'fallback', 'recourse'],
  'ambiguous': ['unclear', 'vague', 'uncertain', 'equivocal', 'indefinite', 'obscure', 'cryptic', 'doubtful', 'dubious', 'ambivalent'],
  'amend': ['revise', 'modify', 'alter', 'change', 'correct', 'improve', 'update', 'adjust', 'reform', 'edit'],
  'annual': ['yearly', 'per year', 'once a year', 'per annum', 'twelve-month', 'seasonal', 'recurrent', 'periodic', 'regular', 'cyclical'],
  'apparent': ['evident', 'obvious', 'clear', 'plain', 'visible', 'manifest', 'noticeable', 'distinct', 'patent', 'unmistakable'],
  'append': ['add', 'attach', 'affix', 'annex', 'adjoin', 'supplement', 'include', 'incorporate', 'insert', 'tack on'],
  'appreciate': ['value', 'recognize', 'understand', 'acknowledge', 'realize', 'comprehend', 'grasp', 'be grateful', 'esteem', 'prize'],
  'arbitrary': ['random', 'chance', 'unpredictable', 'capricious', 'whimsical', 'unreasoned', 'subjective', 'discretionary', 'inconsistent', 'erratic'],
  'aspect': ['feature', 'element', 'facet', 'component', 'part', 'side', 'dimension', 'angle', 'characteristic', 'quality'],
  'assemble': ['gather', 'collect', 'convene', 'congregate', 'meet', 'construct', 'build', 'put together', 'compile', 'accumulate'],
  'assignment': ['task', 'job', 'duty', 'project', 'mission', 'work', 'homework', 'exercise', 'responsibility', 'charge'],
  'attach': ['affix', 'fasten', 'connect', 'join', 'link', 'bind', 'secure', 'fix', 'stick', 'append'],
  'attain': ['achieve', 'reach', 'accomplish', 'obtain', 'gain', 'secure', 'realize', 'acquire', 'earn', 'win'],
  'aware': ['conscious', 'cognizant', 'mindful', 'informed', 'knowledgeable', 'alert', 'awake', 'perceptive', 'familiar', 'enlightened'],
  'behalf': ['interest', 'benefit', 'advantage', 'sake', 'support', 'favor', 'representation', 'name', 'account', 'part'],
  'bias': ['prejudice', 'partiality', 'favoritism', 'inclination', 'tendency', 'slant', 'predisposition', 'preference', 'leaning', 'skew'],
  'bond': ['connection', 'link', 'tie', 'relationship', 'attachment', 'union', 'covenant', 'agreement', 'association', 'affinity'],
  'brief': ['short', 'concise', 'succinct', 'compact', 'summary', 'quick', 'temporary', 'fleeting', 'cursory', 'abbreviated'],
  'bulk': ['majority', 'mass', 'volume', 'size', 'magnitude', 'quantity', 'most', 'greater part', 'preponderance', 'lion share'],
  'capable': ['able', 'competent', 'qualified', 'skilled', 'proficient', 'talented', 'adept', 'accomplished', 'efficient', 'effective'],
  'capacity': ['ability', 'capability', 'power', 'potential', 'volume', 'space', 'size', 'role', 'function', 'position'],
  'category': ['class', 'type', 'group', 'classification', 'division', 'kind', 'sort', 'genre', 'family', 'variety'],
  'cease': ['stop', 'end', 'halt', 'discontinue', 'terminate', 'finish', 'conclude', 'quit', 'desist', 'suspend'],
  'challenge': ['difficulty', 'problem', 'obstacle', 'test', 'trial', 'contest', 'question', 'dispute', 'confront', 'defy'],
  'channel': ['route', 'path', 'way', 'means', 'medium', 'conduit', 'passage', 'avenue', 'outlet', 'course'],
  'chapter': ['section', 'part', 'division', 'segment', 'portion', 'passage', 'episode', 'phase', 'stage', 'period'],
  'chart': ['graph', 'diagram', 'table', 'map', 'plot', 'illustration', 'figure', 'scheme', 'representation', 'visual'],
  'cite': ['quote', 'reference', 'mention', 'refer to', 'note', 'indicate', 'point out', 'name', 'acknowledge', 'credit'],
  'civil': ['public', 'civic', 'municipal', 'community', 'civilian', 'domestic', 'polite', 'courteous', 'refined', 'civilized'],
  'clarify': ['explain', 'elucidate', 'illuminate', 'clear up', 'simplify', 'make clear', 'interpret', 'define', 'specify', 'detail'],
  'classic': ['traditional', 'typical', 'standard', 'archetypal', 'model', 'exemplary', 'definitive', 'timeless', 'enduring', 'vintage'],
  'clause': ['provision', 'stipulation', 'condition', 'article', 'section', 'paragraph', 'term', 'part', 'passage', 'statement'],
  'code': ['rules', 'regulations', 'laws', 'system', 'cipher', 'symbols', 'language', 'program', 'standard', 'protocol'],
  'coherent': ['logical', 'consistent', 'rational', 'organized', 'systematic', 'clear', 'intelligible', 'lucid', 'orderly', 'unified'],
  'coincide': ['correspond', 'match', 'align', 'agree', 'concur', 'coexist', 'synchronize', 'overlap', 'harmonize', 'accord'],
  'collapse': ['fall', 'break down', 'fail', 'crumble', 'disintegrate', 'cave in', 'buckle', 'fold', 'decline', 'founder'],
  'colleague': ['coworker', 'associate', 'peer', 'partner', 'fellow', 'collaborator', 'teammate', 'workmate', 'companion', 'confrere'],
  'commence': ['begin', 'start', 'initiate', 'launch', 'open', 'embark', 'set out', 'kick off', 'inaugurate', 'originate'],
  'comment': ['remark', 'observation', 'statement', 'note', 'opinion', 'view', 'criticism', 'feedback', 'reaction', 'input'],
  'commission': ['committee', 'board', 'panel', 'agency', 'authority', 'assignment', 'task', 'charge', 'mandate', 'fee'],
  'commit': ['pledge', 'promise', 'dedicate', 'devote', 'undertake', 'engage', 'bind', 'obligate', 'vow', 'guarantee'],
  'commodity': ['product', 'goods', 'item', 'merchandise', 'article', 'material', 'resource', 'staple', 'ware', 'stock'],
  'communicate': ['convey', 'express', 'transmit', 'share', 'relay', 'impart', 'inform', 'tell', 'contact', 'correspond'],
  'community': ['society', 'group', 'population', 'public', 'neighborhood', 'locality', 'district', 'residents', 'citizens', 'collective'],
  'compatible': ['consistent', 'harmonious', 'congruent', 'matching', 'suitable', 'appropriate', 'fitting', 'agreeable', 'congenial', 'accordant'],
  'compensate': ['pay', 'reimburse', 'recompense', 'reward', 'remunerate', 'repay', 'make up for', 'offset', 'balance', 'redress'],
  'compile': ['collect', 'gather', 'assemble', 'accumulate', 'amass', 'organize', 'compose', 'arrange', 'put together', 'collate'],
  'complement': ['supplement', 'complete', 'enhance', 'accompany', 'match', 'correspond', 'counterpart', 'addition', 'accompaniment', 'adjunct'],
  'complex': ['complicated', 'intricate', 'involved', 'elaborate', 'difficult', 'compound', 'composite', 'sophisticated', 'multifaceted', 'convoluted'],
  'component': ['part', 'element', 'piece', 'constituent', 'ingredient', 'unit', 'module', 'section', 'segment', 'factor'],
  'compound': ['combination', 'mixture', 'composite', 'blend', 'amalgam', 'complex', 'synthesis', 'union', 'fusion', 'alloy'],
  'comprise': ['consist of', 'include', 'contain', 'encompass', 'be made up of', 'incorporate', 'constitute', 'compose', 'embrace', 'involve'],
  'compute': ['calculate', 'figure', 'reckon', 'determine', 'work out', 'estimate', 'measure', 'assess', 'evaluate', 'quantify'],
  'conceive': ['imagine', 'envision', 'think', 'devise', 'formulate', 'create', 'develop', 'originate', 'visualize', 'picture'],
  'concentrate': ['focus', 'center', 'direct', 'apply', 'intensify', 'condense', 'consolidate', 'converge', 'gather', 'accumulate'],
  'conflict': ['disagreement', 'dispute', 'clash', 'controversy', 'fight', 'battle', 'struggle', 'contention', 'discord', 'opposition'],
  'conform': ['comply', 'follow', 'obey', 'adhere', 'adapt', 'adjust', 'fit', 'match', 'agree', 'correspond'],
  'consent': ['agreement', 'approval', 'permission', 'assent', 'acceptance', 'authorization', 'sanction', 'acquiescence', 'compliance', 'concurrence'],
  'consequent': ['resulting', 'ensuing', 'following', 'subsequent', 'successive', 'sequential', 'attendant', 'resultant', 'consequential', 'derivative'],
  'considerable': ['substantial', 'significant', 'large', 'sizable', 'great', 'extensive', 'notable', 'marked', 'appreciable', 'respectable'],
  'constant': ['continuous', 'continual', 'steady', 'unchanging', 'consistent', 'persistent', 'perpetual', 'unceasing', 'unending', 'permanent'],
  'constrain': ['restrict', 'limit', 'confine', 'restrain', 'inhibit', 'control', 'curb', 'check', 'contain', 'bind'],
  'construct': ['build', 'create', 'make', 'erect', 'assemble', 'fabricate', 'form', 'establish', 'develop', 'devise'],
  'consult': ['confer', 'discuss', 'refer to', 'seek advice', 'deliberate', 'talk', 'advise', 'counsel', 'guide', 'check'],
  'consume': ['use', 'utilize', 'expend', 'eat', 'drink', 'devour', 'deplete', 'exhaust', 'absorb', 'take in'],
  'contact': ['communication', 'connection', 'touch', 'reach', 'get in touch', 'call', 'write', 'approach', 'liaison', 'correspondence'],
  'contemporary': ['modern', 'current', 'present-day', 'recent', 'up-to-date', 'contemporary', 'simultaneous', 'concurrent', 'coexistent', 'synchronous'],
  'contradict': ['oppose', 'refute', 'deny', 'dispute', 'challenge', 'negate', 'counter', 'conflict with', 'disagree', 'controvert'],
  'contrary': ['opposite', 'reverse', 'converse', 'antithetical', 'opposed', 'contradictory', 'conflicting', 'adverse', 'counter', 'different'],
  'contrast': ['difference', 'distinction', 'disparity', 'divergence', 'compare', 'juxtapose', 'differentiate', 'oppose', 'conflict', 'vary'],
  'contribute': ['give', 'donate', 'provide', 'supply', 'add', 'participate', 'help', 'aid', 'assist', 'support'],
  'controversy': ['debate', 'dispute', 'argument', 'disagreement', 'conflict', 'contention', 'quarrel', 'polemic', 'disputation', 'discord'],
  'convene': ['assemble', 'gather', 'meet', 'congregate', 'come together', 'convoke', 'summon', 'call together', 'organize', 'muster'],
  'converse': ['opposite', 'reverse', 'contrary', 'inverse', 'talk', 'speak', 'chat', 'communicate', 'discourse', 'dialogue'],
  'convert': ['change', 'transform', 'alter', 'modify', 'turn', 'switch', 'adapt', 'adjust', 'translate', 'transmute'],
  'convince': ['persuade', 'satisfy', 'assure', 'prove to', 'win over', 'sway', 'influence', 'move', 'convert', 'prevail upon'],
  'cooperate': ['collaborate', 'work together', 'coordinate', 'team up', 'join forces', 'unite', 'partner', 'participate', 'contribute', 'assist'],
  'coordinate': ['organize', 'arrange', 'harmonize', 'synchronize', 'integrate', 'correlate', 'match', 'align', 'manage', 'direct'],
  'core': ['center', 'heart', 'nucleus', 'essence', 'kernel', 'crux', 'foundation', 'basis', 'fundamental', 'essential'],
  'corporate': ['business', 'company', 'commercial', 'organizational', 'collective', 'joint', 'combined', 'unified', 'shared', 'communal'],
  'correspond': ['match', 'agree', 'align', 'conform', 'relate', 'communicate', 'write', 'exchange letters', 'parallel', 'equate'],
  'couple': ['pair', 'two', 'duo', 'twosome', 'combine', 'connect', 'link', 'join', 'unite', 'associate'],
  'credit': ['recognition', 'acknowledgment', 'praise', 'commendation', 'trust', 'belief', 'faith', 'attribute', 'ascribe', 'assign'],
  'criteria': ['standards', 'measures', 'benchmarks', 'requirements', 'guidelines', 'rules', 'principles', 'norms', 'specifications', 'yardsticks'],
  'crucial': ['critical', 'vital', 'essential', 'key', 'important', 'decisive', 'pivotal', 'significant', 'fundamental', 'central'],
  'culture': ['society', 'civilization', 'customs', 'traditions', 'way of life', 'lifestyle', 'heritage', 'arts', 'refinement', 'cultivation'],
  'currency': ['money', 'cash', 'legal tender', 'coinage', 'bills', 'funds', 'acceptance', 'prevalence', 'circulation', 'popularity'],
  'cycle': ['sequence', 'series', 'pattern', 'round', 'rotation', 'circle', 'period', 'phase', 'course', 'circuit'],
  'debate': ['discuss', 'argue', 'dispute', 'deliberate', 'consider', 'contest', 'controversy', 'argument', 'discussion', 'discourse'],
  'decade': ['ten years', 'period', 'era', 'age', 'generation', 'span', 'epoch', 'time'],
  'decline': ['decrease', 'fall', 'drop', 'reduce', 'diminish', 'refuse', 'reject', 'deteriorate', 'worsen', 'weaken'],
  'deduce': ['infer', 'conclude', 'reason', 'derive', 'gather', 'understand', 'work out', 'figure out', 'determine', 'extrapolate'],
  'deny': ['refuse', 'reject', 'refute', 'contradict', 'negate', 'dispute', 'rebut', 'disavow', 'repudiate', 'decline'],
  'depict': ['portray', 'show', 'represent', 'illustrate', 'describe', 'picture', 'render', 'characterize', 'delineate', 'present'],
  'despite': ['in spite of', 'notwithstanding', 'regardless of', 'although', 'even though', 'though', 'for all', 'in defiance of'],
  'detect': ['discover', 'find', 'identify', 'notice', 'perceive', 'spot', 'uncover', 'recognize', 'sense', 'discern'],
  'deviate': ['diverge', 'differ', 'vary', 'depart', 'stray', 'wander', 'digress', 'veer', 'shift', 'deflect'],
  'device': ['tool', 'instrument', 'apparatus', 'gadget', 'mechanism', 'equipment', 'appliance', 'implement', 'machine', 'contrivance'],
  'devote': ['dedicate', 'commit', 'give', 'apply', 'assign', 'allocate', 'consecrate', 'pledge', 'set aside', 'reserve'],
  'differentiate': ['distinguish', 'discriminate', 'separate', 'tell apart', 'contrast', 'divide', 'demarcate', 'identify', 'characterize', 'individualize'],
  'dimension': ['aspect', 'facet', 'feature', 'size', 'extent', 'magnitude', 'measure', 'proportion', 'scope', 'scale'],
  'diminish': ['decrease', 'reduce', 'lessen', 'decline', 'dwindle', 'shrink', 'lower', 'weaken', 'abate', 'subside'],
  'discrete': ['separate', 'distinct', 'individual', 'detached', 'discontinuous', 'disconnected', 'independent', 'particular', 'specific', 'isolated'],
  'discriminate': ['differentiate', 'distinguish', 'tell apart', 'separate', 'discern', 'bias', 'prejudice', 'treat unfairly', 'favor', 'single out'],
  'displace': ['replace', 'move', 'shift', 'remove', 'relocate', 'transfer', 'supplant', 'supersede', 'substitute', 'dislodge'],
  'display': ['show', 'exhibit', 'present', 'demonstrate', 'reveal', 'expose', 'manifest', 'feature', 'showcase', 'illustrate'],
  'dispose': ['arrange', 'place', 'position', 'get rid of', 'discard', 'throw away', 'incline', 'predispose', 'influence', 'lead'],
  'distort': ['twist', 'misrepresent', 'warp', 'deform', 'falsify', 'pervert', 'contort', 'skew', 'bend', 'alter'],
  'diverse': ['varied', 'different', 'various', 'miscellaneous', 'assorted', 'mixed', 'heterogeneous', 'diverse', 'multifarious', 'eclectic'],
  'document': ['record', 'paper', 'file', 'report', 'certificate', 'evidence', 'proof', 'write', 'chronicle', 'register'],
  'domain': ['field', 'area', 'sphere', 'realm', 'territory', 'region', 'province', 'discipline', 'specialty', 'expertise'],
  'domestic': ['home', 'household', 'national', 'internal', 'native', 'local', 'indigenous', 'family', 'private', 'civil'],
  'dominate': ['control', 'rule', 'govern', 'command', 'lead', 'prevail', 'overshadow', 'tower over', 'predominate', 'master'],
  'draft': ['sketch', 'outline', 'plan', 'version', 'write', 'compose', 'draw up', 'formulate', 'prepare', 'design'],
  'drama': ['play', 'theater', 'performance', 'show', 'production', 'excitement', 'tension', 'conflict', 'crisis', 'spectacle'],
  'duration': ['length', 'time', 'period', 'span', 'term', 'extent', 'course', 'continuance', 'timespan', 'stretch'],
  'dynamic': ['energetic', 'active', 'vigorous', 'forceful', 'changing', 'evolving', 'moving', 'lively', 'powerful', 'vital'],
  'eliminate': ['remove', 'get rid of', 'delete', 'erase', 'exclude', 'omit', 'abolish', 'eradicate', 'dismiss', 'drop'],
  'emerge': ['appear', 'arise', 'surface', 'come out', 'develop', 'materialize', 'evolve', 'spring up', 'come forth', 'transpire'],
  'emphasis': ['stress', 'importance', 'weight', 'prominence', 'focus', 'accent', 'attention', 'priority', 'significance', 'highlight'],
  'empirical': ['experimental', 'practical', 'observed', 'experiential', 'factual', 'evidence-based', 'verifiable', 'objective', 'scientific', 'measurable'],
  'enable': ['allow', 'permit', 'empower', 'facilitate', 'make possible', 'authorize', 'qualify', 'equip', 'capacitate', 'sanction'],
  'encounter': ['meet', 'face', 'experience', 'come across', 'confront', 'run into', 'bump into', 'engage', 'find', 'discover'],
  'energy': ['power', 'force', 'strength', 'vigor', 'vitality', 'drive', 'dynamism', 'enthusiasm', 'spirit', 'stamina'],
  'enforce': ['implement', 'apply', 'execute', 'administer', 'carry out', 'impose', 'compel', 'require', 'insist', 'mandate'],
  'enhance': ['improve', 'increase', 'boost', 'augment', 'strengthen', 'intensify', 'amplify', 'elevate', 'upgrade', 'refine'],
  'enormous': ['huge', 'vast', 'immense', 'massive', 'gigantic', 'tremendous', 'colossal', 'mammoth', 'monumental', 'extensive'],
  'ensure': ['make sure', 'guarantee', 'secure', 'assure', 'confirm', 'certify', 'verify', 'safeguard', 'protect', 'warrant'],
  'entity': ['being', 'thing', 'object', 'body', 'organization', 'existence', 'unit', 'individual', 'creature', 'organism'],
  'equate': ['equal', 'compare', 'liken', 'match', 'parallel', 'associate', 'correspond', 'identify', 'equalize', 'balance'],
  'equip': ['provide', 'supply', 'furnish', 'outfit', 'fit out', 'arm', 'prepare', 'ready', 'enable', 'endow'],
  'equivalent': ['equal', 'same', 'comparable', 'corresponding', 'parallel', 'tantamount', 'identical', 'similar', 'matching', 'analogous'],
  'erode': ['wear away', 'corrode', 'deteriorate', 'diminish', 'weaken', 'undermine', 'decay', 'crumble', 'disintegrate', 'degrade'],
  'error': ['mistake', 'fault', 'blunder', 'inaccuracy', 'slip', 'oversight', 'miscalculation', 'flaw', 'defect', 'miscue'],
  'ethical': ['moral', 'right', 'proper', 'principled', 'virtuous', 'honorable', 'just', 'fair', 'upright', 'righteous'],
  'ethnic': ['racial', 'cultural', 'national', 'tribal', 'indigenous', 'native', 'traditional', 'folk', 'minority', 'ancestral'],
  'eventual': ['final', 'ultimate', 'resulting', 'consequent', 'ensuing', 'subsequent', 'later', 'future', 'concluding', 'terminal'],
  'exceed': ['surpass', 'go beyond', 'outdo', 'outstrip', 'transcend', 'top', 'eclipse', 'better', 'beat', 'overtake'],
  'exclude': ['omit', 'leave out', 'eliminate', 'bar', 'ban', 'prohibit', 'reject', 'rule out', 'except', 'shut out'],
  'exhibit': ['display', 'show', 'present', 'demonstrate', 'reveal', 'expose', 'manifest', 'illustrate', 'feature', 'express'],
  'expand': ['enlarge', 'increase', 'extend', 'grow', 'develop', 'broaden', 'widen', 'spread', 'amplify', 'swell'],
  'expert': ['specialist', 'professional', 'authority', 'master', 'guru', 'pundit', 'virtuoso', 'ace', 'adept', 'connoisseur'],
  'explicit': ['clear', 'definite', 'specific', 'precise', 'exact', 'direct', 'unambiguous', 'express', 'plain', 'stated'],
  'exploit': ['use', 'utilize', 'take advantage of', 'manipulate', 'abuse', 'capitalize on', 'employ', 'leverage', 'harness', 'profit from'],
  'expose': ['reveal', 'uncover', 'disclose', 'show', 'display', 'unveil', 'unmask', 'lay bare', 'exhibit', 'present'],
  'external': ['outside', 'outer', 'exterior', 'outward', 'foreign', 'extraneous', 'peripheral', 'surface', 'superficial', 'extrinsic'],
  'extract': ['remove', 'take out', 'draw out', 'pull out', 'obtain', 'derive', 'get', 'withdraw', 'separate', 'isolate'],
  'facilitate': ['help', 'assist', 'aid', 'ease', 'enable', 'simplify', 'smooth', 'expedite', 'further', 'advance'],
  'finite': ['limited', 'bounded', 'restricted', 'fixed', 'definite', 'measurable', 'countable', 'terminable', 'confined', 'circumscribed'],
  'flexible': ['adaptable', 'versatile', 'adjustable', 'elastic', 'pliable', 'supple', 'bendable', 'malleable', 'accommodating', 'variable'],
  'fluctuate': ['vary', 'change', 'shift', 'oscillate', 'swing', 'waver', 'alternate', 'rise and fall', 'undulate', 'vacillate'],
  'forthcoming': ['approaching', 'coming', 'upcoming', 'imminent', 'future', 'impending', 'prospective', 'expected', 'anticipated', 'pending'],
  'fundamental': ['basic', 'essential', 'primary', 'principal', 'key', 'central', 'core', 'vital', 'crucial', 'cardinal'],
  'furthermore': ['moreover', 'additionally', 'besides', 'also', 'in addition', 'what is more', 'further', 'plus', 'as well', 'too'],
  'gender': ['sex', 'sexual identity', 'masculinity', 'femininity', 'male', 'female', 'classification', 'type', 'kind', 'category'],
  'generate': ['produce', 'create', 'make', 'cause', 'bring about', 'give rise to', 'yield', 'spawn', 'engender', 'originate'],
  'generation': ['age group', 'cohort', 'era', 'period', 'age', 'production', 'creation', 'offspring', 'progeny', 'descendants'],
  'globe': ['world', 'earth', 'planet', 'sphere', 'ball', 'orb', 'worldwide', 'international', 'global', 'universal'],
  'goal': ['aim', 'objective', 'target', 'purpose', 'ambition', 'aspiration', 'intention', 'end', 'mission', 'destination'],
  'grade': ['level', 'rank', 'class', 'mark', 'score', 'rating', 'quality', 'standard', 'degree', 'category'],
  'grant': ['give', 'award', 'bestow', 'provide', 'allow', 'permit', 'concede', 'confer', 'endow', 'allocate'],
  'guarantee': ['assure', 'ensure', 'promise', 'warrant', 'pledge', 'certify', 'secure', 'safeguard', 'protect', 'vouch for'],
  'hence': ['therefore', 'thus', 'consequently', 'accordingly', 'so', 'as a result', 'for this reason', 'thereby', 'ergo', 'thence'],
  'highlight': ['emphasize', 'stress', 'underline', 'spotlight', 'feature', 'accentuate', 'point out', 'focus on', 'call attention to', 'showcase'],
  'identical': ['same', 'equal', 'equivalent', 'matching', 'alike', 'indistinguishable', 'duplicate', 'twin', 'uniform', 'similar'],
  'ideology': ['beliefs', 'doctrine', 'philosophy', 'principles', 'ideas', 'creed', 'worldview', 'theory', 'tenets', 'convictions'],
  'ignorance': ['lack of knowledge', 'unawareness', 'unfamiliarity', 'inexperience', 'innocence', 'oblivion', 'nescience', 'unconsciousness', 'stupidity', 'illiteracy'],
  'image': ['picture', 'representation', 'likeness', 'depiction', 'illustration', 'figure', 'icon', 'photograph', 'impression', 'perception'],
  'immigrate': ['migrate', 'move to', 'relocate', 'settle', 'come to', 'resettle', 'transfer', 'transplant', 'emigrate', 'arrive'],
  'impact': ['effect', 'influence', 'consequence', 'result', 'impression', 'repercussion', 'outcome', 'significance', 'bearing', 'force'],
  'implement': ['carry out', 'execute', 'apply', 'put into practice', 'enact', 'realize', 'perform', 'fulfill', 'accomplish', 'achieve'],
  'implicate': ['involve', 'incriminate', 'connect', 'associate', 'link', 'imply', 'suggest', 'entangle', 'embroil', 'concern'],
  'implicit': ['implied', 'understood', 'inferred', 'unspoken', 'tacit', 'indirect', 'suggested', 'inherent', 'latent', 'underlying'],
  'imply': ['suggest', 'indicate', 'hint', 'insinuate', 'intimate', 'mean', 'signify', 'denote', 'connote', 'allude'],
  'impose': ['enforce', 'inflict', 'levy', 'apply', 'force', 'require', 'mandate', 'demand', 'establish', 'institute'],
  'incentive': ['motivation', 'encouragement', 'inducement', 'stimulus', 'spur', 'reward', 'benefit', 'reason', 'motive', 'enticement'],
  'incidence': ['occurrence', 'frequency', 'rate', 'prevalence', 'extent', 'instance', 'case', 'event', 'happening', 'manifestation'],
  'incline': ['tend', 'lean', 'be disposed', 'slope', 'tilt', 'slant', 'gradient', 'prefer', 'favor', 'be prone'],
  'incorporate': ['include', 'integrate', 'combine', 'merge', 'unite', 'blend', 'embody', 'contain', 'encompass', 'absorb'],
  'index': ['list', 'catalog', 'register', 'directory', 'indicator', 'measure', 'guide', 'table', 'reference', 'sign'],
  'indigenous': ['native', 'local', 'aboriginal', 'original', 'endemic', 'autochthonous', 'domestic', 'innate', 'inherent', 'natural'],
  'induce': ['cause', 'bring about', 'produce', 'provoke', 'trigger', 'generate', 'stimulate', 'prompt', 'persuade', 'encourage'],
  'inevitable': ['unavoidable', 'certain', 'inescapable', 'sure', 'definite', 'predetermined', 'fated', 'destined', 'necessary', 'inexorable'],
  'infer': ['deduce', 'conclude', 'gather', 'understand', 'derive', 'reason', 'assume', 'presume', 'surmise', 'extrapolate'],
  'infrastructure': ['framework', 'foundation', 'structure', 'base', 'system', 'network', 'facilities', 'services', 'backbone', 'groundwork'],
  'inherent': ['intrinsic', 'innate', 'built-in', 'natural', 'essential', 'fundamental', 'basic', 'integral', 'inborn', 'native'],
  'inhibit': ['prevent', 'hinder', 'restrain', 'restrict', 'obstruct', 'impede', 'constrain', 'check', 'curb', 'suppress'],
  'initial': ['first', 'beginning', 'starting', 'opening', 'earliest', 'original', 'primary', 'introductory', 'inaugural', 'preliminary'],
  'initiate': ['start', 'begin', 'commence', 'launch', 'introduce', 'originate', 'instigate', 'trigger', 'inaugurate', 'set in motion'],
  'injure': ['hurt', 'harm', 'damage', 'wound', 'impair', 'afflict', 'bruise', 'maim', 'disable', 'cripple'],
  'innovate': ['introduce', 'pioneer', 'create', 'invent', 'develop', 'revolutionize', 'modernize', 'originate', 'design', 'devise'],
  'input': ['contribution', 'data', 'information', 'feedback', 'suggestion', 'advice', 'supply', 'material', 'resource', 'ingredient'],
  'insert': ['put in', 'place', 'add', 'introduce', 'embed', 'inject', 'include', 'incorporate', 'interpose', 'interpolate'],
  'insight': ['understanding', 'perception', 'awareness', 'comprehension', 'wisdom', 'intuition', 'realization', 'enlightenment', 'discernment', 'vision'],
  'inspect': ['examine', 'check', 'scrutinize', 'survey', 'review', 'investigate', 'study', 'look over', 'observe', 'assess'],
  'instance': ['example', 'case', 'occurrence', 'occasion', 'illustration', 'sample', 'specimen', 'situation', 'event', 'incident'],
  'institute': ['establish', 'create', 'found', 'set up', 'start', 'initiate', 'launch', 'inaugurate', 'organization', 'institution'],
  'instruct': ['teach', 'educate', 'train', 'direct', 'tell', 'order', 'command', 'guide', 'inform', 'enlighten'],
  'integral': ['essential', 'fundamental', 'necessary', 'vital', 'basic', 'intrinsic', 'constituent', 'inherent', 'complete', 'whole'],
  'integrate': ['combine', 'merge', 'unite', 'incorporate', 'blend', 'unify', 'amalgamate', 'fuse', 'join', 'coordinate'],
  'integrity': ['honesty', 'honor', 'principle', 'morality', 'ethics', 'uprightness', 'probity', 'virtue', 'wholeness', 'completeness'],
  'intelligence': ['intellect', 'mind', 'brain', 'wit', 'cleverness', 'understanding', 'knowledge', 'wisdom', 'information', 'data'],
  'intense': ['extreme', 'strong', 'powerful', 'severe', 'fierce', 'acute', 'deep', 'concentrated', 'passionate', 'fervent'],
  'interact': ['communicate', 'engage', 'interface', 'connect', 'cooperate', 'socialize', 'relate', 'associate', 'collaborate', 'network'],
  'intermediate': ['middle', 'in-between', 'midway', 'medium', 'moderate', 'transitional', 'mediocre', 'average', 'mediating', 'intervening'],
  'internal': ['inside', 'inner', 'interior', 'domestic', 'native', 'intrinsic', 'inherent', 'inward', 'within', 'private'],
  'interval': ['gap', 'space', 'period', 'pause', 'break', 'intermission', 'interlude', 'lapse', 'hiatus', 'interim'],
  'intervene': ['interfere', 'intercede', 'mediate', 'step in', 'interrupt', 'interpose', 'arbitrate', 'involve oneself', 'intrude', 'come between'],
  'intrinsic': ['inherent', 'essential', 'fundamental', 'basic', 'innate', 'natural', 'integral', 'built-in', 'inborn', 'native'],
  'invest': ['put money into', 'fund', 'finance', 'spend', 'allocate', 'contribute', 'devote', 'commit', 'dedicate', 'endow'],
  'investigate': ['examine', 'study', 'research', 'explore', 'probe', 'inspect', 'scrutinize', 'analyze', 'look into', 'inquire'],
  'invoke': ['call upon', 'appeal to', 'cite', 'refer to', 'summon', 'evoke', 'conjure up', 'mention', 'quote', 'implement'],
  'isolate': ['separate', 'detach', 'segregate', 'insulate', 'quarantine', 'cut off', 'seclude', 'set apart', 'disconnect', 'extract'],
  'journal': ['magazine', 'periodical', 'publication', 'diary', 'log', 'record', 'newspaper', 'gazette', 'chronicle', 'register'],
  'justify': ['explain', 'defend', 'vindicate', 'warrant', 'validate', 'support', 'rationalize', 'substantiate', 'excuse', 'prove'],
  'label': ['tag', 'name', 'mark', 'identify', 'classify', 'categorize', 'designate', 'brand', 'title', 'describe'],
  'layer': ['level', 'tier', 'stratum', 'sheet', 'coating', 'film', 'blanket', 'covering', 'thickness', 'depth'],
  'lecture': ['talk', 'speech', 'address', 'presentation', 'lesson', 'discourse', 'sermon', 'teaching', 'instruction', 'reprimand'],
  'levy': ['impose', 'charge', 'tax', 'collect', 'exact', 'demand', 'assess', 'raise', 'gather', 'requisition'],
  'liberal': ['progressive', 'open-minded', 'tolerant', 'broad-minded', 'generous', 'abundant', 'free', 'permissive', 'lenient', 'flexible'],
  'license': ['permit', 'authorization', 'permission', 'certificate', 'warrant', 'document', 'allow', 'authorize', 'sanction', 'approve'],
  'likewise': ['similarly', 'also', 'too', 'in the same way', 'equally', 'correspondingly', 'by the same token', 'as well', 'additionally', 'moreover'],
  'link': ['connection', 'relationship', 'tie', 'bond', 'association', 'connect', 'join', 'unite', 'relate', 'associate'],
  'locate': ['find', 'discover', 'pinpoint', 'identify', 'determine', 'place', 'position', 'situate', 'establish', 'settle'],
  'logic': ['reasoning', 'rationality', 'sense', 'coherence', 'rationale', 'argument', 'thinking', 'intellect', 'deduction', 'philosophy'],
  'manipulate': ['control', 'influence', 'handle', 'manage', 'exploit', 'maneuver', 'operate', 'use', 'work', 'adjust'],
  'manual': ['handbook', 'guide', 'guidebook', 'instructions', 'directions', 'reference', 'by hand', 'physical', 'non-automatic', 'hand-operated'],
  'margin': ['edge', 'border', 'boundary', 'periphery', 'brink', 'rim', 'verge', 'fringe', 'leeway', 'allowance'],
  'mature': ['adult', 'grown', 'developed', 'ripe', 'full-grown', 'complete', 'evolved', 'sophisticated', 'experienced', 'seasoned'],
  'maximize': ['optimize', 'increase', 'enhance', 'boost', 'amplify', 'raise', 'heighten', 'intensify', 'expand', 'augment'],
  'mechanism': ['process', 'system', 'method', 'means', 'procedure', 'device', 'apparatus', 'machinery', 'technique', 'operation'],
  'media': ['press', 'news', 'journalism', 'communication', 'broadcasting', 'channels', 'outlets', 'publications', 'reporters', 'mass communication'],
  'mediate': ['arbitrate', 'negotiate', 'intervene', 'intercede', 'moderate', 'reconcile', 'resolve', 'settle', 'broker', 'referee'],
  'medical': ['health', 'clinical', 'medicinal', 'therapeutic', 'healing', 'remedial', 'curative', 'healthcare', 'pharmaceutical', 'surgical'],
  'medium': ['means', 'method', 'way', 'channel', 'vehicle', 'instrument', 'average', 'middle', 'moderate', 'intermediate'],
  'mental': ['psychological', 'cognitive', 'intellectual', 'cerebral', 'emotional', 'psychiatric', 'mind', 'inner', 'subjective', 'rational'],
  'migrate': ['move', 'relocate', 'emigrate', 'immigrate', 'transfer', 'travel', 'journey', 'shift', 'resettle', 'transplant'],
  'military': ['armed forces', 'army', 'defense', 'martial', 'soldiers', 'troops', 'warfare', 'combat', 'strategic', 'tactical'],
  'minimal': ['minimum', 'least', 'smallest', 'slightest', 'negligible', 'marginal', 'bare', 'basic', 'token', 'nominal'],
  'minimize': ['reduce', 'decrease', 'lessen', 'diminish', 'lower', 'limit', 'curtail', 'downplay', 'understate', 'belittle'],
  'minimum': ['least', 'lowest', 'smallest', 'minimal', 'slightest', 'bottom', 'base', 'floor', 'baseline', 'least amount'],
  'ministry': ['department', 'office', 'bureau', 'agency', 'service', 'government body', 'administration', 'authority', 'priesthood', 'clergy'],
  'minor': ['small', 'lesser', 'insignificant', 'trivial', 'petty', 'slight', 'unimportant', 'secondary', 'subordinate', 'youth'],
  'mode': ['method', 'way', 'manner', 'means', 'style', 'fashion', 'approach', 'system', 'form', 'technique'],
  'modify': ['change', 'alter', 'adjust', 'adapt', 'revise', 'amend', 'vary', 'transform', 'edit', 'tweak'],
  'monitor': ['observe', 'watch', 'track', 'check', 'supervise', 'oversee', 'survey', 'screen', 'follow', 'scrutinize'],
  'motive': ['reason', 'motivation', 'purpose', 'cause', 'incentive', 'drive', 'intention', 'rationale', 'stimulus', 'goal'],
  'mutual': ['shared', 'common', 'joint', 'reciprocal', 'collective', 'bilateral', 'two-way', 'interactive', 'cooperative', 'communal'],
  'negate': ['nullify', 'cancel', 'invalidate', 'deny', 'contradict', 'refute', 'disprove', 'reverse', 'undo', 'neutralize'],
  'network': ['system', 'web', 'grid', 'structure', 'organization', 'complex', 'connect', 'link', 'communicate', 'interact'],
  'neutral': ['impartial', 'unbiased', 'objective', 'nonpartisan', 'detached', 'disinterested', 'even-handed', 'fair', 'balanced', 'indifferent'],
  'nevertheless': ['however', 'nonetheless', 'still', 'yet', 'even so', 'all the same', 'in spite of that', 'notwithstanding', 'regardless', 'anyway'],
  'nonetheless': ['nevertheless', 'however', 'still', 'yet', 'even so', 'all the same', 'despite that', 'notwithstanding', 'regardless', 'anyway'],
  'notion': ['idea', 'concept', 'thought', 'belief', 'opinion', 'theory', 'impression', 'understanding', 'conception', 'view'],
  'notwithstanding': ['despite', 'in spite of', 'nevertheless', 'nonetheless', 'however', 'yet', 'still', 'although', 'even though', 'regardless'],
  'nuclear': ['atomic', 'thermonuclear', 'molecular', 'central', 'core', 'fundamental', 'essential', 'basic', 'key', 'critical'],
  'objective': ['goal', 'aim', 'target', 'purpose', 'intention', 'impartial', 'unbiased', 'neutral', 'fair', 'factual'],
  'offset': ['counterbalance', 'compensate', 'balance', 'neutralize', 'cancel out', 'make up for', 'counteract', 'equalize', 'nullify', 'negate'],
  'ongoing': ['continuing', 'current', 'in progress', 'underway', 'continuous', 'constant', 'persistent', 'unfinished', 'progressing', 'developing'],
  'option': ['choice', 'alternative', 'possibility', 'selection', 'preference', 'route', 'opportunity', 'way', 'course', 'solution'],
  'orient': ['direct', 'align', 'position', 'adjust', 'adapt', 'familiarize', 'accustom', 'acclimate', 'point', 'guide'],
  'outcome': ['result', 'consequence', 'effect', 'upshot', 'end', 'conclusion', 'product', 'aftermath', 'sequel', 'payoff'],
  'output': ['production', 'yield', 'product', 'result', 'work', 'productivity', 'performance', 'achievement', 'turnout', 'harvest'],
  'overall': ['general', 'total', 'complete', 'comprehensive', 'all-inclusive', 'entire', 'whole', 'collective', 'aggregate', 'global'],
  'overlap': ['coincide', 'intersect', 'converge', 'match', 'correspond', 'duplicate', 'parallel', 'concur', 'agree', 'share'],
  'overseas': ['abroad', 'foreign', 'international', 'external', 'offshore', 'exotic', 'distant', 'remote', 'outlying', 'faraway'],
  'panel': ['board', 'committee', 'group', 'team', 'jury', 'commission', 'council', 'body', 'tribunal', 'forum'],
  'paradigm': ['model', 'pattern', 'example', 'archetype', 'template', 'standard', 'framework', 'prototype', 'ideal', 'exemplar'],
  'paragraph': ['section', 'passage', 'part', 'portion', 'segment', 'division', 'block', 'unit', 'clause', 'subsection'],
  'parallel': ['similar', 'analogous', 'comparable', 'equivalent', 'corresponding', 'matching', 'alike', 'equal', 'simultaneous', 'concurrent'],
  'parameter': ['limit', 'boundary', 'constraint', 'guideline', 'framework', 'specification', 'criterion', 'standard', 'variable', 'factor'],
  'participate': ['take part', 'join in', 'engage', 'contribute', 'be involved', 'partake', 'share', 'cooperate', 'collaborate', 'play a role'],
  'partner': ['associate', 'colleague', 'ally', 'collaborator', 'companion', 'teammate', 'co-worker', 'confederate', 'mate', 'counterpart'],
  'passive': ['inactive', 'submissive', 'docile', 'compliant', 'unresponsive', 'resigned', 'acquiescent', 'uninvolved', 'inert', 'lifeless'],
  'perceive': ['see', 'observe', 'notice', 'detect', 'discern', 'recognize', 'sense', 'feel', 'understand', 'comprehend'],
  'persist': ['continue', 'persevere', 'endure', 'last', 'remain', 'carry on', 'keep on', 'maintain', 'sustain', 'survive'],
  'perspective': ['viewpoint', 'point of view', 'outlook', 'angle', 'stance', 'position', 'attitude', 'approach', 'slant', 'interpretation'],
  'phase': ['stage', 'step', 'period', 'point', 'level', 'cycle', 'chapter', 'part', 'juncture', 'degree'],
  'phenomenon': ['occurrence', 'event', 'happening', 'incident', 'fact', 'circumstance', 'experience', 'situation', 'marvel', 'wonder'],
  'philosophy': ['thinking', 'thought', 'beliefs', 'ideology', 'principles', 'worldview', 'doctrine', 'theory', 'values', 'wisdom'],
  'physical': ['bodily', 'corporeal', 'material', 'tangible', 'concrete', 'substantial', 'solid', 'real', 'actual', 'palpable'],
  'plus': ['and', 'additionally', 'moreover', 'furthermore', 'also', 'as well', 'besides', 'together with', 'in addition to', 'along with'],
  'portion': ['part', 'section', 'segment', 'piece', 'share', 'serving', 'helping', 'allocation', 'fraction', 'percentage'],
  'pose': ['present', 'raise', 'create', 'cause', 'position', 'place', 'assume', 'adopt', 'strike', 'model'],
  'positive': ['favorable', 'good', 'beneficial', 'advantageous', 'constructive', 'affirmative', 'optimistic', 'confident', 'certain', 'definite'],
  'potential': ['possible', 'likely', 'prospective', 'capability', 'capacity', 'promise', 'ability', 'power', 'latent', 'dormant'],
  'practitioner': ['professional', 'expert', 'specialist', 'worker', 'provider', 'practiser', 'doer', 'performer', 'operator', 'implementer'],
  'precede': ['come before', 'go before', 'antecede', 'lead', 'introduce', 'predate', 'herald', 'usher in', 'forerun', 'anticipate'],
  'predict': ['forecast', 'foresee', 'anticipate', 'project', 'prophesy', 'foretell', 'expect', 'envision', 'estimate', 'guess'],
  'predominant': ['main', 'chief', 'primary', 'principal', 'dominant', 'leading', 'major', 'prevailing', 'prominent', 'foremost'],
  'preliminary': ['initial', 'introductory', 'preparatory', 'opening', 'first', 'early', 'preceding', 'prior', 'prefatory', 'starting'],
  'presume': ['assume', 'suppose', 'believe', 'think', 'expect', 'imagine', 'take for granted', 'surmise', 'infer', 'conjecture'],
  'previous': ['earlier', 'prior', 'former', 'preceding', 'past', 'beforehand', 'aforementioned', 'foregoing', 'antecedent', 'last'],
  'primary': ['main', 'principal', 'chief', 'key', 'major', 'fundamental', 'basic', 'essential', 'first', 'leading'],
  'prime': ['main', 'chief', 'principal', 'primary', 'key', 'best', 'top', 'first-rate', 'excellent', 'superior'],
  'principal': ['main', 'primary', 'chief', 'key', 'leading', 'major', 'foremost', 'central', 'fundamental', 'head'],
  'prior': ['earlier', 'previous', 'before', 'preceding', 'former', 'foregoing', 'antecedent', 'past', 'advance', 'preparatory'],
  'priority': ['preference', 'importance', 'precedence', 'primacy', 'urgency', 'concern', 'preeminence', 'first place', 'superiority', 'rank'],
  'professional': ['expert', 'specialist', 'practitioner', 'skilled', 'qualified', 'competent', 'trained', 'experienced', 'proficient', 'career'],
  'prohibit': ['forbid', 'ban', 'bar', 'prevent', 'disallow', 'outlaw', 'proscribe', 'veto', 'restrict', 'stop'],
  'project': ['plan', 'scheme', 'program', 'venture', 'undertaking', 'enterprise', 'assignment', 'task', 'predict', 'forecast'],
  'promote': ['encourage', 'support', 'advance', 'foster', 'further', 'boost', 'advertise', 'publicize', 'champion', 'advocate'],
  'proportion': ['ratio', 'percentage', 'part', 'share', 'portion', 'fraction', 'amount', 'balance', 'relationship', 'symmetry'],
  'prospect': ['possibility', 'chance', 'likelihood', 'probability', 'outlook', 'expectation', 'hope', 'potential', 'opportunity', 'view'],
  'protocol': ['procedure', 'rules', 'regulations', 'code', 'convention', 'custom', 'etiquette', 'system', 'method', 'routine'],
  'psychology': ['mental processes', 'mind', 'behavior', 'psyche', 'mental state', 'mindset', 'mentality', 'thinking', 'cognition', 'consciousness'],
  'publish': ['print', 'issue', 'release', 'produce', 'circulate', 'distribute', 'disseminate', 'announce', 'broadcast', 'make public'],
  'pursue': ['follow', 'chase', 'seek', 'hunt', 'track', 'continue', 'carry on', 'engage in', 'work toward', 'strive for'],
  'qualitative': ['subjective', 'descriptive', 'interpretive', 'non-numerical', 'experiential', 'observational', 'contextual', 'in-depth', 'rich', 'detailed'],
  'quote': ['cite', 'reference', 'repeat', 'recite', 'mention', 'excerpt', 'passage', 'quotation', 'extract', 'citation'],
  'radical': ['extreme', 'fundamental', 'drastic', 'revolutionary', 'thorough', 'complete', 'basic', 'root', 'far-reaching', 'comprehensive'],
  'random': ['arbitrary', 'chance', 'haphazard', 'unpredictable', 'unplanned', 'casual', 'irregular', 'sporadic', 'accidental', 'stochastic'],
  'rational': ['logical', 'reasonable', 'sensible', 'sound', 'intelligent', 'judicious', 'wise', 'prudent', 'sane', 'coherent'],
  'react': ['respond', 'reply', 'answer', 'reciprocate', 'retaliate', 'counter', 'behave', 'act', 'operate', 'function'],
  'recover': ['retrieve', 'regain', 'reclaim', 'get back', 'restore', 'recuperate', 'heal', 'improve', 'rally', 'rebound'],
  'refine': ['improve', 'perfect', 'polish', 'enhance', 'purify', 'clarify', 'hone', 'develop', 'cultivate', 'upgrade'],
  'regime': ['government', 'system', 'administration', 'rule', 'authority', 'establishment', 'leadership', 'regime', 'power', 'control'],
  'register': ['record', 'list', 'catalog', 'log', 'enroll', 'sign up', 'enlist', 'note', 'document', 'chronicle'],
  'regulations': ['rules', 'laws', 'guidelines', 'directives', 'standards', 'codes', 'requirements', 'provisions', 'ordinances', 'statutes'],
  'reinforce': ['strengthen', 'support', 'bolster', 'fortify', 'buttress', 'consolidate', 'enhance', 'intensify', 'supplement', 'back up'],
  'reject': ['refuse', 'decline', 'deny', 'turn down', 'rebuff', 'dismiss', 'repudiate', 'spurn', 'discard', 'veto'],
  'relax': ['rest', 'unwind', 'loosen', 'ease', 'calm', 'reduce', 'lessen', 'slacken', 'moderate', 'soften'],
  'release': ['free', 'liberate', 'discharge', 'let go', 'issue', 'publish', 'announce', 'distribute', 'unveil', 'launch'],
  'reluctance': ['unwillingness', 'hesitation', 'disinclination', 'aversion', 'resistance', 'hesitancy', 'reservation', 'doubt', 'qualm', 'scruple'],
  'rely': ['depend', 'count on', 'trust', 'bank on', 'lean on', 'reckon on', 'have faith in', 'believe in', 'confide in', 'resort to'],
  'remove': ['take away', 'eliminate', 'delete', 'erase', 'extract', 'withdraw', 'dismiss', 'get rid of', 'clear', 'strip'],
  'render': ['make', 'cause to be', 'give', 'provide', 'present', 'deliver', 'perform', 'execute', 'translate', 'interpret'],
  'resolve': ['solve', 'settle', 'determine', 'decide', 'fix', 'sort out', 'work out', 'clear up', 'conclude', 'end'],
  'restrain': ['hold back', 'control', 'check', 'curb', 'limit', 'restrict', 'constrain', 'inhibit', 'suppress', 'contain'],
  'retain': ['keep', 'hold', 'maintain', 'preserve', 'continue', 'save', 'sustain', 'hang on to', 'reserve', 'withhold'],
  'reveal': ['show', 'disclose', 'expose', 'uncover', 'unveil', 'display', 'present', 'divulge', 'make known', 'bring to light'],
  'revenue': ['income', 'earnings', 'receipts', 'proceeds', 'profit', 'returns', 'yield', 'gains', 'takings', 'turnover'],
  'reverse': ['opposite', 'contrary', 'converse', 'invert', 'overturn', 'undo', 'negate', 'cancel', 'revoke', 'repeal'],
  'revise': ['change', 'modify', 'alter', 'amend', 'update', 'edit', 'correct', 'improve', 'rewrite', 'rework'],
  'revolution': ['change', 'transformation', 'upheaval', 'rebellion', 'revolt', 'uprising', 'overthrow', 'innovation', 'breakthrough', 'radical change'],
  'rigid': ['stiff', 'inflexible', 'strict', 'firm', 'hard', 'unyielding', 'unbending', 'fixed', 'set', 'stringent'],
  'route': ['path', 'way', 'road', 'course', 'direction', 'channel', 'passage', 'avenue', 'track', 'line'],
  'scenario': ['situation', 'case', 'circumstance', 'setting', 'scene', 'possibility', 'prospect', 'outline', 'plan', 'sequence'],
  'schedule': ['plan', 'timetable', 'agenda', 'program', 'calendar', 'itinerary', 'list', 'arrange', 'organize', 'set'],
  'scheme': ['plan', 'program', 'system', 'strategy', 'design', 'project', 'arrangement', 'plot', 'procedure', 'framework'],
  'scope': ['range', 'extent', 'reach', 'span', 'breadth', 'compass', 'area', 'sphere', 'domain', 'field'],
  'sequence': ['series', 'order', 'succession', 'progression', 'chain', 'string', 'train', 'course', 'arrangement', 'pattern'],
  'series': ['sequence', 'succession', 'chain', 'string', 'run', 'set', 'group', 'collection', 'array', 'progression'],
  'sex': ['gender', 'sexuality', 'intercourse', 'relations', 'reproduction', 'male', 'female', 'mating', 'coitus', 'copulation'],
  'sole': ['only', 'single', 'exclusive', 'lone', 'solitary', 'unique', 'individual', 'alone', 'singular', 'one'],
  'somewhat': ['rather', 'quite', 'fairly', 'moderately', 'slightly', 'a little', 'to some extent', 'partially', 'relatively', 'pretty'],
  'sophisticated': ['complex', 'advanced', 'refined', 'cultured', 'worldly', 'educated', 'experienced', 'elaborate', 'intricate', 'developed'],
  'sphere': ['area', 'field', 'domain', 'realm', 'province', 'globe', 'ball', 'orb', 'range', 'scope'],
  'stable': ['steady', 'secure', 'firm', 'solid', 'constant', 'unchanging', 'fixed', 'balanced', 'reliable', 'dependable'],
  'statistics': ['data', 'figures', 'numbers', 'facts', 'information', 'stats', 'metrics', 'measurements', 'analytics', 'quantitative data'],
  'status': ['position', 'standing', 'rank', 'state', 'condition', 'situation', 'level', 'grade', 'prestige', 'reputation'],
  'straightforward': ['simple', 'easy', 'clear', 'direct', 'uncomplicated', 'plain', 'honest', 'frank', 'candid', 'forthright'],
  'strategy': ['plan', 'approach', 'method', 'tactic', 'scheme', 'design', 'procedure', 'policy', 'game plan', 'blueprint'],
  'stress': ['emphasize', 'highlight', 'underline', 'accent', 'pressure', 'strain', 'tension', 'worry', 'anxiety', 'burden'],
  'submit': ['present', 'propose', 'offer', 'tender', 'put forward', 'hand in', 'give in', 'yield', 'surrender', 'comply'],
  'subordinate': ['inferior', 'lower', 'junior', 'secondary', 'lesser', 'minor', 'subsidiary', 'auxiliary', 'dependent', 'subservient'],
  'subsequent': ['following', 'later', 'succeeding', 'ensuing', 'next', 'consequent', 'resulting', 'successive', 'after', 'future'],
  'subsidy': ['grant', 'aid', 'assistance', 'support', 'contribution', 'allowance', 'funding', 'payment', 'subvention', 'backing'],
  'substitute': ['replace', 'alternative', 'replacement', 'stand-in', 'surrogate', 'proxy', 'backup', 'deputy', 'exchange', 'swap'],
  'successor': ['heir', 'inheritor', 'replacement', 'follower', 'descendant', 'next in line', 'continuator', 'beneficiary', 'substitute', 'relief'],
  'summary': ['outline', 'overview', 'synopsis', 'abstract', 'digest', 'précis', 'recap', 'rundown', 'review', 'condensation'],
  'supplement': ['addition', 'extra', 'add-on', 'complement', 'extension', 'appendix', 'addendum', 'add to', 'enhance', 'augment'],
  'survey': ['study', 'review', 'examination', 'investigation', 'poll', 'questionnaire', 'research', 'inspect', 'assess', 'evaluate'],
  'survive': ['endure', 'persist', 'last', 'continue', 'remain', 'live on', 'outlive', 'weather', 'withstand', 'pull through'],
  'suspend': ['hang', 'dangle', 'stop', 'halt', 'pause', 'interrupt', 'postpone', 'delay', 'defer', 'discontinue'],
  'sustain': ['maintain', 'keep', 'preserve', 'support', 'uphold', 'continue', 'prolong', 'bear', 'endure', 'withstand'],
  'symbol': ['sign', 'emblem', 'representation', 'icon', 'mark', 'token', 'indicator', 'figure', 'character', 'image'],
  'tape': ['record', 'recording', 'videotape', 'cassette', 'strip', 'band', 'ribbon', 'bind', 'fasten', 'secure'],
  'target': ['goal', 'objective', 'aim', 'purpose', 'mark', 'object', 'subject', 'focus', 'direct at', 'aim at'],
  'task': ['job', 'duty', 'assignment', 'work', 'chore', 'responsibility', 'mission', 'project', 'undertaking', 'function'],
  'team': ['group', 'squad', 'crew', 'unit', 'side', 'party', 'gang', 'band', 'company', 'ensemble'],
  'technique': ['method', 'approach', 'procedure', 'way', 'means', 'system', 'style', 'manner', 'process', 'skill'],
  'temporary': ['short-term', 'provisional', 'interim', 'transient', 'brief', 'fleeting', 'momentary', 'passing', 'impermanent', 'ephemeral'],
  'tense': ['tight', 'taut', 'strained', 'stressed', 'nervous', 'anxious', 'worried', 'uptight', 'rigid', 'stiff'],
  'terminate': ['end', 'stop', 'finish', 'cease', 'conclude', 'close', 'halt', 'discontinue', 'complete', 'wind up'],
  'theme': ['topic', 'subject', 'subject matter', 'idea', 'motif', 'concept', 'thesis', 'message', 'thread', 'essence'],
  'thereby': ['thus', 'therefore', 'by that means', 'as a result', 'consequently', 'accordingly', 'hence', 'so', 'thence', 'in doing so'],
  'thesis': ['argument', 'proposition', 'theory', 'hypothesis', 'premise', 'dissertation', 'paper', 'essay', 'treatise', 'contention'],
  'topic': ['subject', 'theme', 'issue', 'matter', 'question', 'point', 'subject matter', 'area', 'field', 'concern'],
  'trace': ['track', 'find', 'discover', 'detect', 'follow', 'pursue', 'outline', 'sketch', 'mark', 'sign'],
  'tradition': ['custom', 'practice', 'convention', 'ritual', 'habit', 'usage', 'heritage', 'culture', 'institution', 'legacy'],
  'transmit': ['send', 'transfer', 'convey', 'communicate', 'pass on', 'relay', 'broadcast', 'dispatch', 'forward', 'deliver'],
  'transport': ['carry', 'convey', 'move', 'transfer', 'ship', 'haul', 'deliver', 'bring', 'take', 'transmit'],
  'trend': ['tendency', 'direction', 'pattern', 'movement', 'drift', 'inclination', 'shift', 'development', 'fashion', 'vogue'],
  'trigger': ['cause', 'initiate', 'prompt', 'provoke', 'activate', 'spark', 'set off', 'stimulate', 'generate', 'induce'],
  'ultimate': ['final', 'last', 'eventual', 'conclusive', 'terminal', 'end', 'utmost', 'maximum', 'supreme', 'greatest'],
  'undergo': ['experience', 'go through', 'endure', 'suffer', 'face', 'encounter', 'sustain', 'weather', 'withstand', 'bear'],
  'underlie': ['form the basis of', 'be the foundation of', 'support', 'underpin', 'be behind', 'cause', 'account for', 'explain', 'justify', 'ground'],
  'undertake': ['begin', 'start', 'embark on', 'take on', 'attempt', 'try', 'engage in', 'commit to', 'pledge', 'promise'],
  'uniform': ['consistent', 'constant', 'regular', 'even', 'unchanging', 'unvarying', 'same', 'identical', 'homogeneous', 'standardized'],
  'unique': ['one of a kind', 'singular', 'distinctive', 'individual', 'special', 'rare', 'exceptional', 'unusual', 'unparalleled', 'matchless'],
  'utiliz': ['use', 'employ', 'apply', 'exploit', 'harness', 'deploy', 'make use of', 'put to use', 'take advantage of', 'leverage'],
  'valid': ['legitimate', 'legal', 'official', 'binding', 'sound', 'well-founded', 'reasonable', 'logical', 'convincing', 'cogent'],
  'vehicle': ['car', 'transport', 'conveyance', 'means', 'medium', 'instrument', 'channel', 'agency', 'mechanism', 'carrier'],
  'version': ['form', 'variant', 'adaptation', 'rendition', 'interpretation', 'account', 'description', 'edition', 'revision', 'release'],
  'via': ['through', 'by way of', 'by means of', 'using', 'per', 'with', 'by', 'via the medium of', 'utilizing', 'employing'],
  'virtual': ['almost', 'near', 'practically', 'essentially', 'effectively', 'simulated', 'online', 'digital', 'computerized', 'cyber'],
  'visible': ['apparent', 'evident', 'noticeable', 'observable', 'perceptible', 'clear', 'obvious', 'discernible', 'detectable', 'conspicuous'],
  'vision': ['sight', 'eyesight', 'view', 'perception', 'image', 'picture', 'dream', 'aspiration', 'goal', 'plan'],
  'visual': ['optical', 'visible', 'ocular', 'graphic', 'pictorial', 'illustrative', 'photographic', 'observable', 'seeable', 'perceptible'],
  'volume': ['amount', 'quantity', 'capacity', 'size', 'bulk', 'mass', 'magnitude', 'book', 'tome', 'publication'],
  'voluntary': ['willing', 'optional', 'elective', 'discretionary', 'unpaid', 'volunteer', 'free', 'intentional', 'deliberate', 'conscious'],
  'welfare': ['well-being', 'health', 'prosperity', 'happiness', 'benefit', 'good', 'advantage', 'interest', 'security', 'safety'],
  'whereas': ['while', 'although', 'though', 'but', 'on the other hand', 'in contrast', 'conversely', 'when in fact', 'given that', 'considering that'],
  'whereby': ['by which', 'through which', 'by means of which', 'by virtue of which', 'by the terms of which', 'according to which', 'under which'],
  'widespread': ['common', 'prevalent', 'extensive', 'general', 'universal', 'pervasive', 'rife', 'rampant', 'epidemic', 'ubiquitous'],
}

/**
 * Get synonyms for a word
 * @param word The word to find synonyms for
 * @returns Array of synonyms or empty array if none found
 */
export function getSynonyms(word: string): string[] {
  const normalized = word.toLowerCase().trim()
  return thesaurus[normalized] || []
}

/**
 * Find the best synonym suggestion for a word
 * Prioritizes more common/better synonyms
 * @param word The word to suggest a synonym for
 * @returns The suggested synonym or empty string if none found
 */
export function getSuggestedSynonym(word: string): string {
  const synonyms = getSynonyms(word)
  if (synonyms.length === 0) return ''
  // Return the first synonym as the primary suggestion
  return synonyms[0]
}

/**
 * Check if a word has synonyms available
 * @param word The word to check
 * @returns True if synonyms are available
 */
export function hasSynonyms(word: string): boolean {
  return getSynonyms(word).length > 0
}

/**
 * Get all available words in thesaurus
 * @returns Array of all words
 */
export function getAvailableWords(): string[] {
  return Object.keys(thesaurus)
}

// Export the thesaurus object for use by enhanced service
export { thesaurus }

export default thesaurus
